const { spawnSync } = require('node:child_process');

function runCmd(cmd, args, opts) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', ...(opts || {}) });
  if (r.error && r.error.code === 'ENOENT') {
    throw new Error(`${cmd} not found on PATH.`);
  }
  if (r.status !== 0) {
    const stderr = (r.stderr || '').trim();
    throw new Error(`${cmd} ${args[0]} failed (exit ${r.status}): ${stderr || '(no stderr)'}`);
  }
  return r.stdout || '';
}

function buildBody({ issueNumber, commitSha, impl, branch }) {
  const files = impl.filesWritten || [];
  const cmds = impl.commandsRun || [];
  const cost = typeof impl.costUsd === 'number' ? impl.costUsd.toFixed(2) : '0.00';

  const parts = [];
  parts.push(`Closes #${issueNumber}.`);
  parts.push('');
  parts.push('Generated by `@kooleklabs/agentic-app github-sync --execute` from the merged plan at `docs/plans/<slug>.md`.');
  parts.push('');
  parts.push(`WIP commit: \`${commitSha.slice(0, 7)}\` on \`${branch}\`.`);
  parts.push('');

  if (files.length === 0) {
    parts.push('## Summary');
    parts.push('');
    parts.push('⚠️ _No files were written by the implementation pass._ Inspect the agent output before merging.');
    parts.push('');
  } else {
    parts.push('## Files written');
    parts.push('');
    for (const f of files) parts.push(`- \`${f}\``);
    parts.push('');
  }

  if (cmds.length === 0 && files.length > 0) {
    parts.push('## Verification');
    parts.push('');
    parts.push('⚠️ _No shell commands were run during the implementation pass (no test suite invoked)._ Run the project\'s test + lint commands locally before merging.');
    parts.push('');
  } else if (cmds.length > 0) {
    parts.push('## Commands run');
    parts.push('');
    for (const c of cmds) parts.push(`- \`${c}\``);
    parts.push('');
  }

  parts.push('## Cost');
  parts.push('');
  parts.push(`\`$${cost}\` (via \`claude-sonnet-4-6\` by default; see \`--model\` / \`--max-cost-usd\`).`);
  parts.push('');

  parts.push('---');
  parts.push('');
  parts.push('_Review the diff carefully. The agent ran in `bypassPermissions` mode with Write / Edit / Bash — amend this commit or start a fresh branch if anything is off._');

  return parts.join('\n');
}

function openImplPR({
  cwd,
  branch,
  issueNumber,
  featureName,
  base = 'main',
  draft = true,
  impl,
  commitSha,
}) {
  try {
    runCmd('git', ['push', '-u', 'origin', branch], { cwd });
  } catch (err) {
    throw new Error(
      `${err.message}\n` +
      `Hint: if the remote branch already exists, delete it with \`git push origin :${branch}\`.`
    );
  }

  const args = [
    'pr', 'create',
    '--base', base,
    '--title', `implement: ${featureName}`,
    '--body', buildBody({ issueNumber, commitSha, impl, branch }),
  ];
  if (draft) args.push('--draft');

  const stdout = runCmd('gh', args, { cwd });
  const url = stdout.trim();
  const m = url.match(/\/pull\/(\d+)/);
  if (!m) {
    throw new Error(`Could not parse PR number from gh output: ${url}`);
  }
  return { prNumber: Number(m[1]), url };
}

module.exports = { openImplPR };
